Issue 1 optional call args
ninchat/ninchat-js pull request #2
Opened 2017-07-27 12:46 UTC by xsamix

2017-07-27 12:56 UTC, xsamix commented
I didn't commit the builded js yet, as I dunno if there's differences on the results between versions of go & gopherjs (I have go-1.7 on my machine). So that's why labeled as WIP, otherwise ok.

Btw, I thought about checking for arg types from call method so you can just leave onLog (js.Object) away and just define address (string). But, not really sure if that's ok with Go, as args are typed after all. So what I mean with this is, I'd check if onLog is string instead of a function, and if so, assign onLog content to address. Could implement this in js but don't know if that's ok with go and gopherjs.

2017-07-31 07:02 UTC, plokk commented
If I recall correctly, at least onLog should've been optional already, but actually wasn't. I ran into this while making bot example in june. So in that sense this is a good improvement. Can't say anything code-wise tho.

2017-08-07 07:34 UTC, tsavola requested changes

2017-08-07 07:34 UTC, tsavola commented on src/ninchatclient/lib/call.go
>  func call(params map[string]interface{}, onLog *js.Object, address string) *js.Object {
The correct way to detect undefined JavaScript value is to change the Go function signature to
```
func call(params map[string]interface{}, onLog *js.Object, address *js.Object) *js.Object {
```
and then check manually if `address` is `js.Undefined`. Go string may then be extracted with `address.String()`.

2017-11-09 10:32 UTC, xsamix commented
@tsavola ping

2017-11-09 11:51 UTC, tsavola approved these changes

2017-11-09 11:51 UTC, tsavola commented on src/ninchatclient/lib/call.go
> +	var api string
Weird variable name choice...

2017-11-09 12:12 UTC, xsamix commented
@tsavola pong

2017-11-09 12:22 UTC, tsavola approved these changes

2017-11-09 12:22 UTC, tsavola commented on src/ninchatclient/lib/call.go
> +	var apihost string
Ah, now I get (also the original) name! :)

2017-11-09 14:05 UTC, merged